"""Seed content for the 6 AI Challenge workshop questions.

See CLAUDE.md section 5 for the design rationale. Files referenced here are
generated by seed/generate_mock_files.py into backend/data/uploads/.
"""

QUESTIONS = [
    {
        "id": "q1",
        "order_index": 1,
        "department": "Marketing",
        "kind": "simple",
        "title": "Draft a Product Launch Announcement",
        "ai_applicable": "yes",
        "requires_files": False,
        "hide_prompt_steps": False,
        "time_limit_minutes": 10,
        "scenario_text": (
            "Bossard Marketing is launching a new fastener line and needs a LinkedIn "
            "announcement post.\n\n"
            "Product name: EcoDrive Stainless Screws\n"
            "Key features:\n"
            "  1. 30% faster installation thanks to a redesigned drive head\n"
            "  2. Corrosion-resistant coating rated for outdoor / marine use\n"
            "  3. Made from 70% recycled stainless steel\n"
            "Target audience: industrial procurement managers and OEM engineers\n"
            "Desired tone: confident, professional, a little bit excited\n\n"
            "Your task: turn these bullet points into a polished LinkedIn launch post "
            "(roughly 100-150 words), with a short attention-grabbing opening line and "
            "a clear call to action at the end."
        ),
        "files": [],
    },
    {
        "id": "q2",
        "order_index": 2,
        "department": "Sales",
        "kind": "simple",
        "title": "Respond to an Unhappy Customer",
        "ai_applicable": "yes",
        "requires_files": False,
        "hide_prompt_steps": False,
        "time_limit_minutes": 10,
        "scenario_text": (
            "A long-time distributor just sent this complaint email to your sales inbox:\n\n"
            '"Subject: Third late shipment this quarter — reconsidering our supplier\n\n'
            "Hi team,\n\n"
            "This is the third time in two months that our bolt order (PO #48213) has "
            "arrived more than a week late. Our own production line was held up "
            "waiting for stock. We've been ordering from you for six years, but "
            "honestly we are now getting quotes from two other suppliers. I need to "
            "know what is going on and what you are going to do about it, or we will "
            "have to move a significant part of our volume elsewhere.\n\n"
            "Regards,\nProcurement Manager, Delta Manufacturing Sdn Bhd\"\n\n"
            "Your task: draft a professional, empathetic reply that acknowledges the "
            "problem, avoids excuses, and proposes concrete next steps to keep the "
            "relationship (e.g. root cause, compensation/goodwill gesture, follow-up "
            "commitment)."
        ),
        "files": [],
    },
    {
        "id": "q3",
        "order_index": 3,
        "department": "HR",
        "kind": "no_ai",
        "title": "Decide Whether to Terminate an Employee",
        "ai_applicable": "no",
        "requires_files": False,
        "hide_prompt_steps": True,
        "time_limit_minutes": 10,
        "scenario_text": (
            "Warehouse operator case file:\n\n"
            "- 4.5 years tenure, previously rated 'meets expectations' every year\n"
            "- 3 late clock-ins in the last 2 months (previously never late)\n"
            "- 1 safety violation 3 weeks ago (not wearing required PPE on the floor), "
            "verbal warning given\n"
            "- Team lead reports the employee has been 'distracted and quiet' lately\n"
            "- In a private conversation, the employee mentioned a family member is "
            "seriously ill and they've been struggling to arrange caregiving\n"
            "- HR policy allows termination for repeated safety violations, but this "
            "is a first written incident\n\n"
            "Your task: decide the final disciplinary outcome (e.g. termination, "
            "written warning + support plan, temporary accommodation, etc.) and, more "
            "importantly, write down WHY you would not (or should not) simply hand "
            "this decision to an AI tool. Think about legal liability, local labor-law "
            "compliance, the need for human empathy and context, and who is "
            "accountable for a decision that materially affects someone's livelihood."
        ),
        "files": [],
    },
    {
        "id": "q4",
        "order_index": 4,
        "department": "Inventory",
        "kind": "excel",
        "title": "Identify Urgent Reorder Items",
        "ai_applicable": "yes",
        "requires_files": True,
        "hide_prompt_steps": False,
        "time_limit_minutes": 15,
        "scenario_text": (
            "Download the attached inventory file (inventory_stock.xlsx). It lists "
            "current stock, reorder point, average monthly usage, and lead time for "
            "every SKU in the fasteners warehouse.\n\n"
            "Your task: open the file, copy the relevant rows/columns into your AI "
            "tool, and produce a prioritized reorder list: which SKUs need to be "
            "ordered urgently, how many units to order, and a rough stockout-risk "
            "rating (High / Medium / Low) for each. Explain your prioritization logic."
        ),
        "files": [
            {
                "filename": "inventory_stock.xlsx",
                "filetype": "xlsx",
                "description": "Current stock levels, reorder points and usage rates across 20 SKUs.",
            }
        ],
    },
    {
        "id": "q5",
        "order_index": 5,
        "department": "Finance",
        "kind": "pdf",
        "title": "Extract Contract Risk Clauses",
        "ai_applicable": "yes",
        "requires_files": True,
        "hide_prompt_steps": False,
        "time_limit_minutes": 15,
        "scenario_text": (
            "Download the attached supplier agreement (supplier_contract.pdf).\n\n"
            "Your task: extract the payment terms, late-delivery penalty clause, "
            "termination clause, and currency/FX adjustment clause, then summarize "
            "them as a short risk brief for the finance manager, including 2-3 "
            "recommended negotiation points before this contract is renewed."
        ),
        "files": [
            {
                "filename": "supplier_contract.pdf",
                "filetype": "pdf",
                "description": "Mock supplier agreement with payment, penalty, termination and FX clauses.",
            }
        ],
    },
    {
        "id": "q6",
        "order_index": 6,
        "department": "Sales & Marketing",
        "kind": "combined",
        "title": "Build a Win-Back Campaign for Declining Customers",
        "ai_applicable": "yes",
        "requires_files": True,
        "hide_prompt_steps": False,
        "time_limit_minutes": 20,
        "scenario_text": (
            "Download both attached files:\n"
            "  - customer_sales.xlsx — monthly order volume per customer for the "
            "last 6 months\n"
            "  - market_report.pdf — a short market/competitor snapshot\n\n"
            "Your task: combine both sources. First identify the top 5 customers "
            "with the clearest declining order trend. Then draft a tailored "
            "win-back email plus a promotion angle for each, referencing relevant "
            "market conditions from the PDF (e.g. competitor pricing moves, demand "
            "shifts) to make the pitch credible."
        ),
        "files": [
            {
                "filename": "customer_sales.xlsx",
                "filetype": "xlsx",
                "description": "6-month order volume history for 15 customers.",
            },
            {
                "filename": "market_report.pdf",
                "filetype": "pdf",
                "description": "Short competitor and market trend snapshot.",
            },
        ],
    },
]
